spring:
  profiles: default

datasource:
  master:
      driver-class-name: "com.mysql.jdbc.Driver"
      url: "jdbc:mysql://gaesoosa-db.cllxzz8hai1n.us-east-1.rds.amazonaws.com:3306/gaesoosa?useUnicode=true&charaterEncoding=utf-8"
      user-name: "gaemaster"
      password: "gaemaster"
      initial-size: 10
      max-active: 10
      max-idle: 10
      min-idle: 10
      max-wait: 3000
